### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by damien122** [jshttp/basic-auth#22]
Hi,

could you please explain how to logout a user after successfull login?

**Comment by dougwilson** [comment]
Hi @damien122, all this module does is parse the `Authorization` header provided by the client. How the client implements log out varies by the client and you will probably have to reference the documentation for the given client.

The TL;DR is that you should not use basic auth with actual user logins, since in most clients, it's almost impossible to perform a logout (or it's a really rough experience).
